name: SDK Repo

on:
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"
      - "README.md"
      - "LICENSE"
      - "NOTICE"
      - "CITATION.cff"
      - ".gitignore"
      - "src/**"
      - "test/**"
      - "tsconfig*.json"
      - "tools/**"
      - ".github/workflows/publish.yml"
      - ".github/workflows/sdk-workspace.yml"
  push:
    branches:
      - main
    paths:
      - "package.json"
      - "package-lock.json"
      - "README.md"
      - "LICENSE"
      - "NOTICE"
      - "CITATION.cff"
      - ".gitignore"
      - "src/**"
      - "test/**"
      - "tsconfig*.json"
      - "tools/**"
      - ".github/workflows/publish.yml"
      - ".github/workflows/sdk-workspace.yml"

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Verify Repo
        run: npm run verify
